name: meta_audio
description: meta_audio will give you an ability to parse metadata from audio files.
version: 0.0.1
homepage: https://github.com/SKKbySSK/meta_audio

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MetaAudioPlugin
      android:
        pluginClass: MetaAudioPlugin
        package: work.ksprogram.meta_audio
